import {
  BETA_LABEL_SEGMENT,
  DEMO_LABEL_SEGMENT,
  PROTO_LABEL_SEGMENT,
  SAMPLE_LABEL_SEGMENT,
} from "../roms/rom-label-segments.constants.js";

const UNRELEASED_ROM_LABEL_SEGMENTS = [
  BETA_LABEL_SEGMENT,
  DEMO_LABEL_SEGMENT,
  PROTO_LABEL_SEGMENT,
  SAMPLE_LABEL_SEGMENT,
];

export default UNRELEASED_ROM_LABEL_SEGMENTS;
