const ERROR_CODE_NAMES = [
  "APP_ENTRY_EXISTS_ERROR",
  "APP_NOT_FOUND_ERROR",
  "APP_VALIDATION_ERROR",
  "APP_WRONG_TYPE_ERROR",
  "DEVICE_FILE_IO_EXISTS_ERROR",
  "DEVICE_FILE_IO_LS_ERROR",
  "FS_CIRCULAR_REFERENCE_ERROR",
  "FS_FILE_EXISTS_ERROR",
  "FS_NOT_FOUND_ERROR",
  "FS_UNAUTHORIZED_ERROR",
  "FS_WRONG_TYPE_ERROR",
  "SFTP_BAD_CREDENTIALS_ERROR",
  "SFTP_BAD_PATH_ERROR",
  "SFTP_CONNECTION_ERROR",
  "SFTP_DISCONNECTION_ERROR",
  "SFTP_NOT_FOUND_ERROR",
  "SFTP_UNAUTHORIZED_ERROR",
  "SFTP_WRONG_TYPE_ERROR",
  "UNKNOWN_ERROR",
] as const;

export default ERROR_CODE_NAMES;
