import {
  BETA_LABEL_SEGMENT,
  DEMO_LABEL_SEGMENT,
  PROTO_LABEL_SEGMENT,
  SAMPLE_LABEL_SEGMENT,
} from "./label-segments.constants.js";

const UNRELEASED_LABEL_SEGMENT_LIST = [
  BETA_LABEL_SEGMENT,
  DEMO_LABEL_SEGMENT,
  PROTO_LABEL_SEGMENT,
  SAMPLE_LABEL_SEGMENT,
];

export default UNRELEASED_LABEL_SEGMENT_LIST;
