const UNWANTED_EXACT_LABELS_BASE_LIST: string[] = [
  "Digital" /* 139 results */,
  "Evercade" /* 111 results */,
  "Kiosk" /* 39 results */,
  "Switch Online" /* 38 results */,
  "Limited Run Games" /* 29 results */,
  "Namcot Collection" /* 21 results */,
  "Atari Flashback" /* 19 results */,
  "Animal Crossing" /* 18 results */,
  "GameCube" /* 18 results */,
  "Cowabunga Collection" /* 17 results */,
  "e-Reader" /* 13 results */,
  "Retro-Bit" /* 13 results */,
  "Castlevania Anniversary Collection" /* 13 results */,
  "Castlevania Advance Collection" /* 12 results */,
  "Batteryless" /* 12 results */,
  "Earlier" /* 11 results */,
  "The Cowabunga Collection" /* 11 results */,
  "QUByte Classics" /* 11 results */,
  "Namco Museum Archives Vol 1" /* 11 results */,
  "Namco Museum Archives Vol 2" /* 11 results */,
  "FamicomBox" /* 11 results */,
  "Arcade" /* 10 results */,
  "Capcom Town" /* 10 results */,
  "Atari Anthology" /* 10 results */,
  "Retro-Bit Generations" /* 9 results */,
  "Debug" /* 7 results */,
  "Limited Edition" /* 6 results */,
  "Easy" /* 5 results */,
  "Activision Anthology - Remix Edition" /* 4 results */,
  "Strictly Limited Games" /* 3 results */,
  "Capcom Classics Mini Mix" /* 3 results */,
  "Aleste Collection" /* 3 results */,
  "Seiken Densetsu Collection" /* 3 results */,
  "Metal Gear Solid Collection" /* 3 results */,
  "SNK 40th Anniversary Collection" /* 3 results */,
  "Debug Version" /* 2 results */,
  "Easy Version" /* 2 results */,
  "GameCube Edition" /* 2 results */,
  "Multicart Rip" /* 2 results */,
  "No Music" /* 1 result */,
  "Anniversary Edition" /* 1 result */,
  "Source Code" /* 1 result */,
  "No Link Cable" /* 1 result */,
  "Light Phaser" /* 1 result */,
  "No SRAM" /* 1 result */,
  "Other Control" /* 1 result */,
  "Sega 3D Classics" /* 1 result */,
  "Very Easy Version" /* 1 result */,
  "Extra Controller" /* 1 result */,
  "Preliminary Speed Version" /* 1 result */,
  "Keihin Ban" /* 1 result */,
];

export default UNWANTED_EXACT_LABELS_BASE_LIST;
