const UNWANTED_EXACT_LABELS_BASE_LIST: string[] = [
  "Pirate" /* 1154 results */,
  "GB Compatible" /* 904 results */,
  "Digital" /* 139 results */,
  "Evercade" /* 111 results */,
  "NP" /* 84 items */,
  "Byte-Off 2019" /* 61 results */,
  "Byte-Off 2020" /* 50 items */,
  "Switch" /* 39 results */,
  "Kiosk" /* 39 results */,
  "Switch Online" /* 38 results */,
  "GBA Jam 2024" /* 37 results */,
  "Extract" /* 30 results */,
  "Namcot Collection" /* 21 results */,
  "NESDev 2016" /* 16 results */,
  "Atari Flashback" /* 19 results */,
  "Animal Crossing" /* 18 results */,
  "GameCube" /* 18 results */,
  "NESDev 2022" /* 16 results */,
  "Cowabunga Collection" /* 17 results */,
  "NESDev 2018" /* 14 results */,
  "NESDev 2017" /* 14 results */,
  "e-Reader" /* 13 results */,
  "Retro-Bit" /* 13 results */,
  "Castlevania Anniversary Collection" /* 13 results */,
  "Piko Interactive" /* 13 results */,
  "NESDev 2014" /* 12 results */,
  "Steam" /* 12 results */,
  "Castlevania Advance Collection" /* 12 results */,
  "Batteryless" /* 12 results */,
  "Earlier" /* 11 results */,
  "The Cowabunga Collection" /* 11 results */,
  "QUByte Classics" /* 11 results */,
  "Namco Museum Archives Vol 1" /* 11 results */,
  "Namco Museum Archives Vol 2" /* 11 results */,
  "FamicomBox" /* 11 results */,
  "No flash saving" /* 10 results */,
  "IE Institute" /* 10 results */,
  "Arcade" /* 10 results */,
  "Capcom Town" /* 10 results */,
  "Atari Anthology" /* 10 results */,
  "Robert L Bryant" /* 10 results */,
  "NintendoAge" /* 9 results */,
  "Retro-Bit Generations" /* 9 results */,
  "NESDev 2011" /* 8 results */,
  "Datach" /* 7 results */,
  "Debug" /* 7 results */,
  "Incube8 Games" /* 6 results */,
  "GB Showdown" /* 5 results */,
  "NEO Coding Compo 2013" /* 5 results */,
  "Easy" /* 5 results */,
  "itch.io" /* 5 results */,
  "The Retro Room" /* 4 results */,
  "Coolboy" /* 4 results */,
  "Activision Anthology - Remix Edition" /* 4 results */,
  "Dreamcast" /* 4 results */,
  "Itch.io" /* 3 results */,
  "Capcom Classics Mini Mix" /* 3 results */,
  "Aleste Collection" /* 3 results */,
  "Seiken Densetsu Collection" /* 3 results */,
  "Metal Gear Solid Collection" /* 3 results */,
  "SNK 40th Anniversary Collection" /* 3 results */,
  "NEO Compo 2012" /* 3 results */,
  "Pixel Heart" /* 2 results */,
  "iam8bit" /* 2 results */,
  "GB Compo 2023" /* 2 results */,
  "Debug Version" /* 2 results */,
  "Easy Version" /* 2 results */,
  "GameCube Edition" /* 2 results */,
  "Multicart Rip" /* 2 results */,
  "RetroZone" /* 2 results */,
  "Aladdin Compact Cartridge" /* 2 results */,
  "Intellivision" /* 2 results */,
  "Jeffrey Wittenhagen's" /* 2 results */,
  "No Music" /* 1 result */,
  "Source Code" /* 1 result */,
  "No Link Cable" /* 1 result */,
  "Light Phaser" /* 1 result */,
  "No SRAM" /* 1 result */,
  "Other Control" /* 1 result */,
  "Sega 3D Classics" /* 1 result */,
  "Very Easy Version" /* 1 result */,
  "Extra Controller" /* 1 result */,
  "Preliminary Speed Version" /* 1 result */,
  "Keihin Ban" /* 1 result */,
  "Batteryless Generic Save Flash Cartridge Version" /* 1 result */,
  "Batteryless Save Flash Cartridge Version" /* 1 result */,
  "EGS" /* 1 result */,
  "SMS Power! 2023 Compo" /* 1 result */,
  "Samsung" /* 1 result */,
  "Renkaban" /* 1 result */,
  "JR Nishi-Nihon Presents" /* 1 result */,
  "PDroms Competition 4.01" /* 1 result */,
  "Battery Save Version" /* 1 result */,
  "No Logo Version" /* 1 result */,
  "RetroGameCon 5 Edition" /* 1 result */,
  "Game Boy Advance" /* 1 result */,
  "NES Mini Version" /* 1 result */,
  "Robert Bryant" /* 1 result */,
  "Super 808 Extract" /* 1 result */,
  "SPC009 Extract" /* 1 result */,
];

export default UNWANTED_EXACT_LABELS_BASE_LIST;
