import {
  ATARI_2600,
  ATARI_7800,
  FINAL_BURN_NEO,
  NINTENDO_ENTERTAINMENT_SYSTEM,
  NINTENDO_GAMEBOY,
  NINTENDO_GAMEBOY_ADVANCE,
  NINTENDO_GAMEBOY_COLOR,
  SEGA_GAMEGEAR,
  SEGA_MASTERSYSTEM,
  SUPER_NINTENDO_ENTERTAINMENT_SYSTEM,
} from "./console-names.constants.js";

const ALL_CONSOLE_NAMES = [
  ATARI_2600,
  ATARI_7800,
  SEGA_GAMEGEAR,
  NINTENDO_GAMEBOY,
  NINTENDO_GAMEBOY_ADVANCE,
  NINTENDO_GAMEBOY_COLOR,
  SEGA_MASTERSYSTEM,
  NINTENDO_ENTERTAINMENT_SYSTEM,
  SUPER_NINTENDO_ENTERTAINMENT_SYSTEM,
  FINAL_BURN_NEO,
] as const;

export default ALL_CONSOLE_NAMES;
